# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy

# More GitHub Actions for Azure: https://github.com/Azure/actions

 

#Change the name to match your course name

#Example name: Deploy HTML Files to AppService - COURSENAME

name: Deploy HTML Files to AppService - CMST387

on:

  push:

    branches:

      - main

jobs:

  build-and-deploy:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@main
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build with Parcel
      run: npm run build

    - name: Deploy to Azure Web App

      uses: azure/webapps-deploy@v1

      with:

        app-name: 'CMST387-UMGC-jwashington110'

        slot-name: 'production'

        publish-profile: ${{ secrets.AppServiceCMST387 }}

        package: './dist'
